# Generated by Django 5.1.2 on 2026-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0007_commissiondetail3_percentage_of_particulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionslip',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionslip3',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
