# Generated by Django 5.1.2 on 2026-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0008_commissionslip_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_commissions',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen_receivables',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen_tranches',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen_unapproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
