# Generated by Django 5.1.2 on 2026-02-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0009_profile_last_seen_commissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_seen_commissions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_seen_receivables',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_seen_tranches',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_seen_unapproved',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('commission', 'Commission'), ('tranche', 'Tranche'), ('receivable', 'Receivable'), ('system', 'System')], default='system', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
