# Generated by Django 5.1.2 on 2026-02-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0010_remove_profile_last_seen_commissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranchepayment',
            name='past_due_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('tranche', 'Tranche'), ('receivable', 'Receivable'), ('system', 'System'), ('warning', 'Warning')], default='system', max_length=20),
        ),
    ]
